#开发环境配置文件
spring:
  redis:
    host: 10.10.0.94
    password:
    port: 6379
    database: 2
    pool:
      max-active: 30    # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1    # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8    # 连接池中的最大空闲连接
      min-idle: 0    # 连接池中的最小空闲连接
    timeout: 20000    # 连接超时时间（毫秒）
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://10.10.0.83:3306/yex?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false # 内网服务器
    username: prod
    password:
    driver-class-name: com.mysql.jdbc.Driver
    sql-script-encoding: utf-8
    initialSize: 5 #初始化大小
    minIdle: 5 #最小
    maxActive: 100 #最大
    maxWait: 60000 #配置获取连接等待超时的时间
    timeBetweenEvictionRunsMillis: 60000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    minEvictableIdleTimeMillis : 300000 #配置一个连接在池中最小生存的时间，单位是毫秒
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true #打开PSCache
    maxPoolPreparedStatementPerConnectionSize: 20 #指定每个连接上PSCache的大小

eureka:
  client:
    serviceUrl:
      defaultZone: http://root:111111@localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
