#开发环境配置文件
spring:
  datasource:
    username: test
    password: hndchtest
    url: jdbc:mysql://47.107.106.12:3306/trade_system?characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      minimum-idle: 1
      idle-timeout: 60000
      maximum-pool-size: 10
      max-lifetime: 1800000
      pool-name: HikariCP
      connection-timeout: 30000
      connection-test-query: SELECT 1
      validation-timeout: 30000
